### ISSUE TITLE
Inconsistences between themes

### ISSUE THREAD

**Issue by popenke** [dracula/jetbrains-legacy#13]
I found some inconsistencies between Xcode's Dracula theme and JetBrains

- Xcode
![screen shot 2017-07-06 at 10 14 47](https://user-images.githubusercontent.com/395142/27913035-2a86dad0-6235-11e7-949b-02ce9102f7aa.png)

- JetBrains
![screen shot 2017-07-06 at 10 22 58](https://user-images.githubusercontent.com/395142/27913036-2a8853e2-6235-11e7-96ae-2e7adde0175e.png)

Both codes are Swift. Since I'm using both Xcode and AppCode, if themes be the same it would help me find things easier.

**Comment by john-eevee** [comment]
This kind of bug is being tracked at dracula/dracula-theme#232
The implementation for JetBrains took as reference the Atom theme, the most complete at the time.
Since I did not own an macOS system I can't make a AppCode flavored theme, since JetBrains love to map things differently. If you want to provide compatibility with AppCode (Swift & Obj-C++) feel free to PR (as side note, take the implmentation reference from [VS Code](https://github.com/dracula/visual-studio-code))
