### ISSUE TITLE
Source Code Pro messes up character display

### ISSUE THREAD

**Issue by apexJCL** [dracula/jetbrains-legacy#15]
## Current configuration

Webstorm 2017.2.1
Windows 10 (Latin-American Spanish)

## Issue

Bad character encoding display, editor and terminal are affected

## What I've done

Issue seems to be related with the default font used (Source Code Pro), because when I change it to my usual default (Fira Code).

I don't know if my font is messed up or if it's a bug known to the font itself.

## Monokai theme activated
![image](https://user-images.githubusercontent.com/4037632/28973303-7bab6870-78f8-11e7-8277-c7d2963062bb.png)

![image](https://user-images.githubusercontent.com/4037632/28973342-98fde4ac-78f8-11e7-8cc5-2827f68dc16c.png)

## Dracula theme activated

![image](https://user-images.githubusercontent.com/4037632/28973440-cf07a132-78f8-11e7-8454-1f91cbddd926.png)

**Comment by john-eevee** [comment]
This issue is usually caused by the OTF version of the Source Code Pro installed or none at all, if you wish to use SCP, please uninstall the current you have installed and install the TTF version, for better compatibility with Java, [here is a guide](http://sticksnglue.com/wordpress/source-code-pro-phpstorm-the-plot-thickens/) for more detailed fixes. The issue relies on the JDK running the editor, not a font one.
