### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by john-eevee** [dracula/jetbrains-legacy#33]
I @sleepiejohn, do not use Jetbrains IDEs anymore, so if you want to be a maintainer comment here so we can make you, as soon as some one can take over I will step down.

**Comment by Glennmen** [comment]
I use Jetbrains IDEs but have no experience in theme development.
I would like to maintain this project as much as I can and try to look into what is needed if we want to release a Jetbrains theme plugin.

**Comment by potb** [comment]
@WhiteVermouth released a Dracula theme (updated two days ago)...
He might be interested in maintaining this project

**Comment by john-eevee** [comment]
@zenorocha  Could you take a look on making @Glennmen and @WhiteVermouth members?

**Comment by WhiteVermouth** [comment]
Since version 2019.1, IntelliJ IDEA and other IntelliJ based JetBrains IDEs add support for custom UI.
As mentioned by @YaourtGG I've created a [Dracula UI theme plugin](https://plugins.jetbrains.com/plugin/12275-dracula-theme), and the project is maintained under my personal [repository](https://github.com/WhiteVermouth/jetbrains-dracula). And of course I"m willing to be the  "official" JetBrains theme maintainer, just tell me what should I do.

**Comment by john-eevee** [comment]
Just merge PR that adds or fixes color mismatches, or fix something if you can, and if possible add more features, such as your theme for the UI. :)

**Comment by WhiteVermouth** [comment]
Dracula UI Plugin is totally a new project, it includes both UI theme and Editor Color Schema, it may be difficult to make a PR onto this repository.

**Comment by john-eevee** [comment]
ping @zenorocha

**Comment by hacknug** [comment]
Hey @WhiteVermouth 👋 

Just sent you an invitation to join the organization. Once you accept you'll be able to transfer the repo to the org (make sure you do it this way so GitHub takes care of redirecting people landing on the old link).

Let me know once it's done or if you have any questions 👍

**Comment by hacknug** [comment]
_New_ version of the theme with UI support [is now a part of the organization](https://github.com/dracula/jetbrains) (thank you @WhiteVermouth). This repo will now be used for the old version of Jetbrains.

Closing since I don't think we need any new maintainers for this version. If anyone has any issues and can't use the newer version, please let me know so we can rethink this 👍
